export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS"
export const FETCH_POST = "FETCH_POST"
export const CREATE_POST = "CREATE_POST"
export const DELETE_POST = "DELETE_POST"
export const POST_VOTE = 'POST_VOTE'
export const FETCH_POSTS_BY_CATEGORY = 'FETCH_POSTS_BY_CATEGORY'

export const SET_POSTS_SORTING = "SET_POSTS_SORTING"

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'

